### PR TITLE
Clarify distinction between scheduler and worker pods

### PR DESCRIPTION
**Pull request by droctothorpe**
Currently, the only way to differentiate the scheduler pods from the worker pods when running `kubectl get pods` is the length of the uid at the end of the pod name.

For example:
```
❯ kgp
NAME                                            READY   STATUS    RESTARTS   AGE
dask-gateway-68h7l                              1/1     Running   0          24h
dask-gateway-6db85d6aa6e9416ca92d91fe520e1b20   1/1     Running   0          23h
```

This is problematic from an administrative standpoint and reduces clarity in our Kubecost Prometheus dashboard.

The change also includes the cluster name in the worker pod name so that we can see, at a glance, which schedulers are tied to which workers.

Also, @jcrist, how would you feel about using `dg` as the prefix instead of `dask-gateway` to reduce the length of the pod name?

### CODE REVIEW

**Comment by jcrist** [comment]
Note that we do set a label `app.kubernetes.io/component` to `scheduler` or `worker` for scheduler and worker pods respectively. I'm happy to change how we do things though. Will have to think about abbreviating `dask-gateway-` to `dg-`, we'd still want to make sure the meaning is clear.

**Comment by droctothorpe** [comment]
For sure, the label is helpful programmatically -- this is more of an operational improvement for cluster admins (with the added benefit of improving our Grafana integration).

**Comment by droctothorpe** [comment]
Added Gil's [suggestion](https://github.com/dask/dask-gateway/pull/257#issuecomment-617808178). Hoping it addresses the CI issue.

**Comment by droctothorpe** [comment]
Confirmed that it resolved the CI issue.

**Comment by droctothorpe** [comment]
Hey, @jcrist. Checking in about the status of this PR.

**Comment by jcrist** [comment]
Apologies for the delay @droctothorpe. I've updated this PR to drop the `-gateway` component from all k8s object names. It wasn't necessary, and made the names overly verbose.

**Comment by droctothorpe** [comment]
No worries. Thanks, Jim!

**Pull request merged**
