### PR TITLE
Move to dask org

### LINKED ISSUE #105: Finish move to dask org
- [ ] Update links
- [ ] Move CI
- [ ] Move docs

### PR DESCRIPTION
**Pull request by jcrist**
Fixes #105.

### CODE REVIEW

**Comment by mrocklin** [comment]
Woot!

What are some other things we should do here?  Should we add a link under the dask setup docs?

Push things to https://gateway.dask.org ?

**Comment by jcrist** [comment]
> Push things to https://gateway.dask.org ?

https://github.com/dask/dask-gateway/issues/106

**Comment by jcrist** [comment]
Would you want something in the dropdown? Or just in the setup docs page?

**Comment by mrocklin** [comment]
Ah, I was coming back here to apologize for not seeing that yet.  Going through e-mail oldest to newest is dangerous :)

**Comment by mrocklin** [comment]
I was thinking here: 

Screen Shot 2019-09-18 at 2 39 04 PM

We could even just link out directly to gateway.dask.org from there.

I think that the dropdown is also a good idea, but I would probably add that in later after dask-gateway gets more traction.  I'm happy either way though.

**Comment by jcrist** [comment]
Sure, I can write something up.

**Comment by jcrist** [comment]
One downside of the move is that builds are *significantly* slower, since we're now competing with dask's travis ci queue :/. May want to move to azure or something else with more builds per org.

**Comment by mrocklin** [comment]
Making it easier to move projects to Azure sounds good to me. Marius was
looking at this in https://github.com/dask/community/issues/1

**Pull request merged**
