### PR TITLE
Bump dask and distributed to 2022.02.0

### PR DESCRIPTION
**Pull request by consideRatio**

### CODE REVIEW

**Comment by jrbourbeau** [comment]
FYI 2022.02.0 isn't on `conda-forge` yet, but should be in the next few hours

**Comment by martindurant** [comment]
ready to test now? The format thing is still here, I see.

**Comment by consideRatio** [comment]
I updated the comments to reference conda-forge versions instead of PyPI versions since we install from conda-forge.

I've rebased this PR on top of #477 which will make us not run into unrelated `black` formatting failures.

**Comment by jacobtomlinson** [comment]
Woo pre-commit CI looks good here.

**Pull request merged**
